site_name: Myfirebase docs

theme:
  logo:
    icon: 'docs/img/favicon.png'

# Configuration
theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

repo_name: myfirebase/myfirebase
repo_url: https://github.com/myfirebase/myfirebase

pages:

- Welcome: index.md

- Getting Started:
    - 'Installation': 'installation.md'
    - 'Directory Structure': 'directory-structure.md'

- The Basics:
    - "Components": 'components.md'
    - "Routing": 'routing.md'
    - "State Managment System": 'store.md'

- Database:
    - "Realtime Database and Cloud Firestore": 'database.md'

- Managing SCSS/SASS:
    - 'Material design and SASS/SCSS': 'style.md'

- Functionalities: 
    - 'Authentication': 'authentication.md'
    - 'Cloud Storage': 'storage.md'
    - 'Cloud Functions': 'cloud-functions.md'
    - 'Cloud Messaging': 'cloud-messaging.md'

- Deep Dive:
    - 'Middlewares (Global Navigation guards)': 'global-guard.md'
    - 'Firebase Admin (Feature request)': 'admin.md'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)


extra:
  logo: 'img/MyFireBase.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
